FROM node:14

WORKDIR /app

# Add node modules (bin) to the path env variable
ENV PATH /app/node_modules/.bin:$PATH

# Copy over dependancies
COPY ./config/frontend.json ./package.json

# Copy over the custom env variables
COPY ./config/.frontend.env ./.env.local

# Install the dependancies
RUN npm install --silent

# Deploy
EXPOSE $PORT
CMD ["npm", "start"]
